name: demo-serverless-cd-workflow

on:
  workflow_call:
    inputs:
      environmentTarget:
        description: 'where to release (sandbox, staging or production)'
        required: true
        type: string
        default: 'sandbox'
      releaseVersion:
        description: 'release version to be deployed'
        required: true
        type: string
        default: 'release'

jobs:
  continuos-deployment-job:
    environment: ${{inputs.environmentTarget}}
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
       name: ${{inputs.releaseVersion}}-ci

    - name: "Deploy stage"
      run: echo "Deploy started!"
    
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - run: aws lambda update-function-code --function-name=LambdaUdeA --zip-file=fileb://${{inputs.releaseVersion}}.zip