name: demo-serverless-ci-cd-workflow

run-name: ${{ github.run_id }}-UdeA-Workflow-Execution

concurrency: 
  group: default 
  #cancel-in-progress: true #cancel any currently running job or workflow in the same concurrency group.

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: choice
        options:
          - 'sandbox'
          - 'development'
        required: true
        default: 'sandbox'
      infraestructure:
        description: Environment to deploy
        type: choice
        options:
          - 'Lambda'
          - 'AzureFunction'
        required: true
        default: 'Lambda'

jobs:
  continuos_integration_job:
    uses: ./.github/workflows/demo-serverless-ci-workflow.yaml
    with:
      infraestructure_target: ${{ inputs.infraestructure }}
      node_version: ${{ inputs.infraestructure == 'Lambda' && '14.x' || '18.x' }}
      folder_target: ${{ inputs.infraestructure == 'Lambda' && './HelloUdeALambda/index.js' || '* -x "node_modules/*"' }}
    secrets: inherit

  # continuos_deployment_job:
  #   needs: continuos_integration_job
  #   uses: ./.github/workflows/demo-serverless-cd-workflow.yaml
  #   with:
  #     environmentTarget: ${{ inputs.environment }}
  #     releaseVersion: ${{ needs.continuos_integration_job.outputs.artifact_base_name }}
  #   secrets: inherit
